import type TelegramBot from 'node-telegram-bot-api';
import { getTelegramBot } from '../../clients/telegramClient';
import { RODAPE_UX } from '../../config/constants';

export async function handleStart(chatId: number, bot: TelegramBot = getTelegramBot()): Promise<void> {
  await bot.sendMessage(
    chatId,
    [
      '👋 *Bem-vindo ao MyFinances!*',
      '',
      '📝 *Registrar gastos* — mande em linguagem natural:',
      '• "Gastei 45 no almoço no pix"',
      '• "Ifood de 50 dividido com minha irmã"',
      '• "Tênis 300 em 3x no crédito"',
      '• "Jantar 120 dividido em 3 com João e Maria"',
      '',
      '📊 *Consultas* — também em linguagem natural:',
      '• "Quanto gastei com transporte mês passado?"',
      '• "O que gastei com alimentação em agosto?"',
      '• "Manda a planilha de setembro" → exporta CSV',
      '',
      '⚡ *Comandos rápidos*:',
      '',
      '/patrimonio — patrimônio consolidado (ativos, caixinhas, ações, dívidas)',
      '/saldo — saldo real em conta vs saldo livre (Safe-to-Spend)',
      '/investimentos — caixinhas (% CDI com rendimento) e renda variável',
      '/ajustar_saldo <conta> <valor> — definir saldo inicial/conciliar',
      '/resumo — resumo do mês (categorias, métodos, alertas)',
      '/fatura — fatura do cartão de crédito',
      '/dividas — quem te deve (e despesas divididas)',
      '/gastos [n] — últimos n lançamentos',
      '/grafico — gráfico PNG por categoria',
      '/insight — análise IA com projeção de fechamento',
      '',
      '💳 *Cartões e vales*:',
      '/cartao — listar cartões/vales',
      '/cartao add <nome> <dia> [credito|vr|va] — adicionar',
      '/cartao principal <nome> — definir como principal',
      '/cartao fatura <nome> — ver fatura do período',
      '/cartao remover <nome> — remover cartão/vale',
      '',
      '💰 *Metas e poupança*:',
      '/meta — ver metas de orçamento (alertas 🟡80% 🔴100%)',
      '/meta <categoria> <limite> — definir meta',
      '/poupanca — metas de poupança de longo prazo',
      '/poupanca definir <nome> <valor> [AAAA-MM] — criar meta',
      '/poupanca add <nome> <valor> — adicionar aporte',
      '',
      '✈️ *Modo viagem*:',
      '/viagem — ver cotações (USD/EUR)',
      '/viagem registrar <valor> <moeda> — converter para BRL',
      '',
      '⚙️ *Utilidades*:',
      '/pago <nome> [valor] — registrar pagamento recebido',
      '/desfazer — desfazer último lançamento',
      '/apagar <id> — apagar lançamento específico',
      '/recorrente — despesas fixas mensais',
      '/exportar [gastos|dividas] [AAAA-MM] — exportar CSV',
      '/status — uptime, latência e versão',
      '',
      RODAPE_UX,
    ].join('\n'),
    { parse_mode: 'Markdown' }
  );
}
